# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5913f8fb802c288dc952b1872987509f846bbb398934b608cdea826994a07cbe27c45270f0fdcfa7b8de7be4fc7fbd3cf4b8a9b588d4ccb17b5b15752cb515af

test:
  secret_key_base: aa933b6dd65dbf153463b0c06f31ecaf1d79fcb8c470a4de96bbdddf2e66902aecb34f408ec56b60dc5b2d71a25d14cfb0971e86d14d260a702db1e254fb7763

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
